#
#   BatteryInventory.py -- Included by BatDev.py terminal monitor
#

inventory = {
    'A' : {'brand':'GP', 'size':'AA', 'mAh':'1300', 'note':'gone squirrely'},
    'B' : {'brand':'GP', 'size':'AA', 'mAh':'1300'},
    'C' : {'brand':'GP', 'size':'AA', 'mAh':'1300'},
    'D' : {'brand':'RadioShack', 'size':'AA', 'mAh':'2500'},
    'E' : {'brand':'GP/KR', 'size':'AA', 'mAh':'700', 'note':'destroyed by MOSFET failure'},
    'F' : {'brand':'GP', 'size':'D', 'mAh':'7000'},
    'G' : {'brand':'Duracell', 'size':'AA', 'mAh':'2400'},
    'H' : {'brand':'GP', 'size':'AA', 'mAh':'2200'},
    'I' : {'brand':'GP', 'size':'AA', 'mAh':'1300'},
    'J' : {'brand':'GP', 'size':'AA', 'mAh':'700'},
    'K' : {'brand':'GP', 'size':'AA', 'mAh':'700'},
    'L' : {'brand':'GP', 'size':'D', 'mAh':'7000'},
    'M' : {'brand':'RadioShack', 'size':'AA', 'mAh':'2500'},
    'N' : {'brand':'Duracell', 'size':'AA', 'mAh':'2400'},
    'O' : {'brand':'Ray-o-Vac', 'size':'AA', 'mAh':'2400'},
    'P' : {'brand':'Ray-o-Vac', 'size':'AA', 'mAh':'2400'},
    'Q' : {'brand':'Ray-o-Vac', 'size':'AA', 'mAh':'2400'},
    'R' : {'brand':'Ray-o-Vac', 'size':'AA', 'mAh':'2400'},
    'S' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'T' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'U' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'V' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'W' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'X' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'Y' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    'Z' : {'brand':'Eneloop', 'size':'AA', 'mAh':'1900'},
    '1' : {'brand':'Duracell', 'size':'AA', 'mAh':'2400'},
    '2' : {'brand':'Duracell', 'size':'AA', 'mAh':'2400'},
    'AB': {'brand':'GP', 'size':'C', 'mAh':'2200'},
    'AC': {'brand':'GP', 'size':'C', 'mAh':'2200'},
    'AD': {'brand':'GP', 'size':'C', 'mAh':'2200'},
    'AE': {'brand':'Panasonic', 'size':'C-NiCd', 'mAh':'1500'},
    'AF': {'brand':'GP', 'size':'C', 'mAh':'1300'},
    'AG': {'brand':'GP', 'size':'AA', 'mAh':'700'},
    'AH': {'brand':'GP', 'size':'D', 'mAh':'7000', 'note':'sucks 3 amps and stays at 350mV'},
    'AI': {'brand':'GP', 'size':'AA', 'mAh':'700'},
    'AK': {'brand':'GP', 'size':'AA', 'mAh':'700'},
    'AL': {'brand':'GP', 'size':'AA', 'mAh':'1300', 'note':'lazurus'}
}
